### ISSUE TITLE
get_hr_all() bug - athlete_id

### ISSUE THREAD

**Issue by conordurkin** [irickman/whoop-downloader#1]
Hi @irickman - I think there's a bug in the **get_hr_all** function (as well as in the **get_hr_timeframe** function). 

Looking at line 280 of whoop_download.py, I see:

`ul='''https://api-7.whoop.com/users/24590/metrics/heart_rate?end={}&order=t&start={}&step=6'''.format(end,start)
`

I assume that /24590/ section is actually referencing your specific athlete ID. I think this should be replaced with:

`ul='''https://api-7.whoop.com/users/{}/metrics/heart_rate?end={}&order=t&start={}&step=6'''.format(athlete_id,end,start)
`

Line 555 (within the **get_hr_timeframe** function) has a corresponding issue.

**Comment by irickman** [comment]
Thanks @conordurkin spot on! I'll fix it right now! That function takes forever to run which is why no one noticed until now!
